feat: integrate wolfsburg campus #359
42atomys/stud42 pull request #376
Opened 2023-01-08 22:25 UTC by mdabir1203

**Relative Issues:** 
Resolve #359 feat: integrate wolfsburg campus 
**Describe the pull request**

Added the Wolfsburg campus in the cluster map.
**Checklist**

- [X] I have linked the relative issue to this pull request
- [ ] I have made the modifications or added tests related to my PR
- [ ] I have added/updated the documentation for my RP
- [ ] I put my PR in Ready for Review only when all the checklist is checked

**Breaking changes ?**
yes/no

**Additional context**

Cluster map configuration row might have slight mistakes

2023-01-10 01:19 UTC, mdabir1203 commented
Cluster map design is finalized and fixed.

2023-01-10 23:55 UTC, 42Atomys commented
@mdabir1203 Thanks for your contribution, I will review your work in the week / by the week end. :)

If you have any staff contact on your campus, tell him to send me a message on 42 Slack to validate with him the integration (legal stuffs)

2023-01-15 14:28 UTC, mdabir1203 commented
@42Atomys Did anyone reach out to you and also can you provide me with your slack name

2023-04-18 13:02 UTC, 42Atomys commented
@mdabir1203 Hello, do you have any news about 42 Wolfsburg ?
I try to go forward with pull requests.

Thanks you in advance !

2023-04-19 22:28 UTC, mdabir1203 commented
@42Atomys  I will get back to them again.

2023-04-24 23:57 UTC, mdabir1203 commented
@42Atomys I spoke with them and they said we still need 2/3 weeks max as the linux migration is ongoing which will also change the cluster map

2023-07-23 15:37 UTC, 42atomys commented
@mdabir1203 Hi, I've returned to inquire about the status of the "cluster map" change. I've noticed that this pull request has been inactive due to lack of response. Please be advised that without a response, this pull request will automatically close in 30 days.

I will handle all communications and approval processes with the staff members. There's no need for you to make further inquiries.

2023-07-23 17:37 UTC, mdabir1203 commented
Hey there was no visible change and I believe they were stalling it for no reason :D

2023-07-27 14:51 UTC, mdabir1203 reviewed
fixed the merge conflicts

2023-08-02 11:14 UTC, 42atomys approved these changes

2023-08-02 11:14 UTC, 42atomys commented on web/ui/src/lib/clustersMap/types.d.ts
> +  | 'mulhouse';
```suggestion
  | 'mulhouse'
  | 'wolfsburg';
```

2023-08-02 14:25 UTC, mdabir1203 commented
Is there anything required to fix that frontend merging fix from my side ?

2023-08-02 23:12 UTC, 42atomys requested changes

2023-08-02 23:12 UTC, 42atomys commented on web/ui/src/lib/clustersMap/campus/wolfsburg.ts
> +export class Malaga extends Campus implements ICampus {
I don't see that, wrong class naming 👀

ℹ️ You can run `yarn make-pretty` to lint your changes

2023-08-02 23:13 UTC, 42atomys commented
Really sorry, thanks to unit test to raise the point, the class name has miss named, and I don't see that on the multiple reviews I made..

2023-10-02 12:59 UTC, 42atomys commented
@mdabir1203 Great news ! staff approve it 🎉 

I will update the branch and merge it, wolfsburg campus will be present in 0.31 💯 
You can start to spread the love 💜

2023-10-02 13:13 UTC, 42atomys approved these changes

2023-10-02 13:16 UTC, merged